[user]
save_user = true

# [network]
# # interface = "eth0"
# # local_address = "0.0.0.0"
# # local_port = 0
# # remote_address = "10.110.61.3"
# # remote_port = 61440
# # timeout = 5

# [process.retry]
# # None to inifinite
# count = 3
# timeout = 5
